#include "zscript/weapons.zsc"
#include "zscript/cast.zsc"

CLASS BadassPlayer : DoomPlayer replaces DoomPlayer { 
	Default {
		Player.DisplayName "The Bad*ss";
		Player.StartItem "SingularBullet";
		Player.StartItem "MarineGrenade";
		Player.StartItem "BadassFist";
		Player.StartItem "Clip", 1;
		Player.StartItem "RocketAmmo", 1 ;
		Player.WeaponSlot 1, "BadassFist", "SawSaw";
		Player.WeaponSlot 2, "SingularBullet";
		Player.WeaponSlot 3, "DumbassShitFuckDickCockShotgun", "DuperShotgun";
		Player.WeaponSlot 4, "SmallButPackingChaingun";
		Player.WeaponSlot 5, "MarineGrenade", "MarineLauncher";
		Player.WeaponSlot 6, "RechargablePlasmaRifleModelv1";
		Player.WeaponSlot 7, "BCG9000";
		Player.Colorset 8, "Saver310",0xC8, 0xCF,  0xCD;
	}
}

// xdeath replacements
CLASS CorpseTosser : Cyberdemon replaces Cyberdemon { 
	Default {
		Tag "Corpse Tosser";
	}
	States
	{
		XDeath:
			CYBG A 4;
			CYBG B 4 A_XScream;
			CYBG C 4 A_NoBlocking;
			CYBG D -1;
			Stop;
	}
}

CLASS Trilobyte : Cacodemon replaces Cacodemon { 
	Default {
		Tag "Trilobyte";	
	}
	States
	{
		XDeath:
			HEAD M 5;
			HEAD N 5 A_XScream;
			HEAD O 5 A_NoBlocking;
			HEAD PQ 5;
			HEAD R -1;
			Stop;
	}
}

// custom monsters
CLASS FucketSpawnLocation : PainElemental { // 26016 
	Default {
		
		Tag "Fucket Spawner";
	}
	States 
	{
		Missile:
			PAIN A 0 A_StartSound("IWANT3BIGMAC",CHAN_AUTO);
			PAIN E 5 A_FaceTarget;
			PAIN A 5 A_FaceTarget;
			PAIN E 5 A_FaceTarget;
			PAIN A 5 A_FaceTarget;
			PAIN F 5 Bright A_FaceTarget;
			TNT1 A 0 A_StartSound("Sraka",CHAN_AUTO);
			PAIN F 0 Bright A_SpawnProjectile("FucketGrenadeGravity", 32, 0, -10);
			PAIN F 0 Bright A_SpawnProjectile("FucketGrenadeGravity", 32, 0, 0);
			PAIN F 0 Bright A_SpawnProjectile("FucketGrenadeGravity", 32, 0, 10);
			PAIN A 15 A_FaceTarget;
			PAIN E 5 A_FaceTarget;
			PAIN A 5 A_FaceTarget;
			PAIN E 5 A_FaceTarget;
			PAIN A 5 A_FaceTarget;
			Goto See;
		Death:
			PAIN H 8 Bright;
			PAIN I 8 Bright A_Scream;
			PAIN JK 8 Bright;
			PAIN L 1 Bright A_SpawnProjectile("FucketGrenadeGravity", 32, 0, 0, 0, CMF_AIMDIRECTION);
			PAIN L 1 Bright A_SpawnProjectile("FucketGrenadeGravity", 32, 0, 0, 90, CMF_AIMDIRECTION);
			PAIN L 1 Bright A_SpawnProjectile("FucketGrenadeGravity", 32, 0, 0, 180, CMF_AIMDIRECTION);
			PAIN L 1 Bright A_SpawnProjectile("FucketGrenadeGravity", 32, 0, 0, 270, CMF_AIMDIRECTION);
			PAIN M 8 Bright;
			Stop;
	}
}

CLASS TheNuker : Cyberdemon  { //26017
	Default {
		
		Obituary "$OB_NUKE_TRIPOD";
		Tag "The Nuker";
	}
	States
	{
		Missile:
			CYBR EEEF 8 A_FaceTarget;
			CYBR F 4 A_SpawnProjectile("PlasmaTesticle");
			CYBR A 8 A_FaceTarget;
			CYBR FFF 2 A_SpawnProjectile("PlasmaTesticle");
			Goto See;
		XDeath:
			CYBG A 4;
			CYBG B 4 A_XScream;
			CYBG C 4 A_NoBlocking;
			CYBG D -1;
			Stop;
	}
}

CLASS NuclearFucket : CustomInventory  {//26018
	Default {
		Tag "Nuclear Fucket";
		Inventory.PickupMessage "$STEPPEDNUCLEARFUCKET";
	}
	States {
		Spawn:
			PLAY ABCD 6 Bright A_SetScale(1,0.40);
			Loop;
		Pickup:
			TNT1 A 0
			{
			    A_StartSound("Sraka");
			    A_SpawnItemEx("PlasmaNuke");
			}
	}
}

CLASS TechnoSpiderDriver : SpiderMastermind { // 26019
	Default {
		
		Tag "Technospider w/ Tough Sailor";
	}
	States
	{
		Death:
			SPID J 20 A_Scream;
			SPID K 5
			{
			    A_NoBlocking();
			    A_SpawnItemEx("DriverSailor");
			}
			SPID LMNOPQR 10;
			SPID S -1;
			Stop;
	}
}

CLASS DriverSailor : WolfensteinSS  { //26020
	Default {
		
		Health 100;
		Speed 12;
		PainChance 200;
		ReactionTime 2;
		Dropitem "ClipBox";
		Tag "Tough Sailor";
	}
	States
	{
		Missile:
			SSWV E 3 A_FaceTarget;
			SSWV F 3 A_FaceTarget;
			SSWV G 1 Bright A_CPosAttack;
			SSWV G 1 Bright A_CPosAttack;
			SSWV F 3 A_FaceTarget;
			SSWV G 1 Bright A_CPosAttack;
			SSWV G 1 Bright A_CPosAttack;
			SSWV F 1 A_CPosRefire;
			Goto Missile+1;
		Pain:
			SSWV H 1;
			SSWV H 2 A_Pain;
			Goto See;
		Death:
			SSWV N 0;
			Goto XDeath;
		XDeath:
			SSWV N 5;
			SSWV O 2 A_StartSound("wolfss/death");
			SSWV O 3 A_XScream;
			SSWV P 5 A_NoBlocking;
			SSWV QRSTU 5;
			SSWV V -1;
			Stop;
		Raise:
			SSWV V 2 A_StartSound("sailor/raise");
			SSWV UTSRQPON 2;
			Goto See;
	}
}

CLASS FakeDeathSailor : WolfensteinSS  { //26021
	Default {
		
		GibHealth 30;
		DropItem "";
		ReactionTime 2;
		Tag "Fake Death Sailor";
	}
	States
	{
		Death:
			SSWV I 5;
			SSWV J 5 A_Scream;
			SSWV K 5 A_NoBlocking;
			SSWV L 5;
			SSWV M 30;
			SSWV L 2 A_StartSound("sailor/raise");
			SSWV KJI 2;
			SSWV I 0 A_SpawnItemEx("FakeDeathSailor");
			Stop;
		XDeath:
			SSWV N 5;
			SSWV O 5 A_XScream;
			SSWV P 0 A_SpawnItemEx("Clip");
			SSWV P 5 A_NoBlocking;
			SSWV QRSTU 5;
			SSWV V -1;
			Stop;
	}
}

CLASS WorkerZombie : ZombieMan { //26022 
	Default {
		
		Health 10;
		Speed 10;
		PainChance 200;
		DropItem "SingularBulletAmmo";
		Tag "Worker Zombie";
	}
	States
	{
		Spawn:
			POSS ABCDBADADBDCACABDACABCD 15 A_Look;
			Loop;
		See:
			POSS AABBCCDD 3 A_Chase("Melee");
			Loop;
		Melee:
			POSS E 10 A_CustomMeleeAttack(10,"skeleton/melee","skeleton/swing");
			POSS A 4;
			Goto See;
	}
}

CLASS NukeBarrel : ExplosiveBarrel { // 26023
	Default {
		
		Tag "Nuke Barrel";
	}
	States
	{
		Spawn:
			NAR1 AB 6;
			Loop;
		Death:
			NEXP A 5 Bright;
			NEXP B 5 Bright A_Scream;
			NEXP C 5 Bright;
			NEXP D 5 Bright A_SpawnItemEx("PlasmaNuke");
			NEXP E 10 Bright;
			Stop;
	}
}

CLASS Convicts : ACTOR { //32420
	Default {
		
		Radius 20;
		health 9800;
		Height 56;
		Obituary "$OB_CONVICTS";
		Speed 9;
		PainChance 200;
		Mass 200;
		+AMBUSH;
		+SOLID;
		+SHOOTABLE;
		
	}
	States
	{
		Spawn:
			CONV A 10 A_Look;
			Loop;
		See:
			CONV A 2;
			CONV A 2
			{
			    A_Chase();
			    A_chase();
			}
			Goto TrueSee;
		TrueSee:
			CONV A 2
			{
			    A_Chase();
			    A_Chase();
			    A_Chase();
			}
			Loop;
		Missile:
			CONV A 3 A_FaceTarget;
			CONV A 2
			{
			    A_SpawnItem("BulletPuff");
			    A_SpawnItem("BulletPuff");
			}
			CONV F 2
			{
			    A_SpawnProjectile("BulletGuru", 64, 0, 0, 0, 0);
			    A_SpawnProjectile("BulletGuru", 64, 0, 0, 0, 0);
			    A_SpawnProjectile("BulletGuru", 64, 0, 0, 0, 0);
			    A_SpawnProjectile("BulletGuru", 64, 0, 0, 0, 0);
			    A_SpawnProjectile("BulletGuru", 64, 0, 0, 0, 0);
			    A_SpawnProjectile("BulletGuru", 64, 0, 0, 0, 0);
			}
			CONV A 3
			{
			    A_Chase();
			    A_Chase();
			}
			CONV A 8 A_Chase();
			CONV A 3 A_Chase();
			CONV A 8
			{
			    A_Chase();
			    A_Chase();
			}
			CONV A 3
			{
			    A_Chase();
			    A_Chase();
			    A_Chase();
			}
			CONV A 8 A_Chase;
			CONV A 3
			{
			    A_Chase();
			    A_Chase();
			}
			CONV A 8
			{
			    A_Chase();
			    A_Chase();
			    A_Chase();
			    A_Chase();
			}
			CONV A 3
			{
			    A_Chase();
			    A_Chase();
			}
			CONV F 4 A_JumpIfTargetInLOS("Missile", 1);
			goto TrueSee;
		Pain:
			CONV A 2;
			CONV A 2 A_Pain;
			Goto TrueSee;
		Death:
			CONV I 8 A_Scream;
			CONV J 8;
			CONV K 8;
			CONV L 8;
			CONV M -1;
			Stop;
	}
}

CLASS BulletGuru : doomimpball { 
	Default {
		
		speed 69;
		SeeSound "weapons/pistol";
		Damage 5;
		Decal "Scorch";
		Obituary "$OB_CONVICTS";
		+RIPPER;
	}
	states
	{
		spawn:
			RFBT B 1;
			loop;
			
			
	}
}
